// ------------------------------------
// Constants
// ------------------------------------
export const NOTEBOOK_CREATE_START    = 'NOTEBOOK_CREATE_START'
export const NOTEBOOK_CREATE_BEGIN    = 'NOTEBOOK_CREATE_BEGIN'
export const NOTEBOOK_CREATE_FAILURE  = 'NOTEBOOK_CREATE_FAILURE'
export const NOTEBOOK_CREATE_SUCCESS  = 'NOTEBOOK_CREATE_SUCCESS'

export const NOTEBOOK_LIST_BEGIN      = 'NOTEBOOK_LIST_BEGIN'
export const NOTEBOOK_LIST_FAILURE    = 'NOTEBOOK_LIST_FAILURE'
export const NOTEBOOK_LIST_SUCCESS    = 'NOTEBOOK_LIST_SUCCESS'

export const NOTEBOOK_ROOT_LIST       = 'NOTEBOOK_ROOT_LIST'

export const NOTEBOOK_SETTING_START    = 'NOTEBOOK_SETTING_START'
export const NOTEBOOK_SETTING_BEGIN    = 'NOTEBOOK_SETTING_BEGIN'
export const NOTEBOOK_SETTING_FAILURE  = 'NOTEBOOK_SETTING_FAILURE'
export const NOTEBOOK_SETTING_SUCCESS  = 'NOTEBOOK_SETTING_SUCCESS'

export const NOTEBOOK_MERGE_BEGIN      = 'NOTEBOOK_MERGE_BEGIN'
export const NOTEBOOK_MERGE_FAILURE    = 'NOTEBOOK_MERGE_FAILURE'
export const NOTEBOOK_MERGE_SUCCESS    = 'NOTEBOOK_MERGE_SUCCESS'

export const NOTEBOOK_LIST_SELECT      = 'NOTEBOOK_LIST_SELECT'
export const NOTEBOOK_LIST_JUSTIFY     = 'NOTEBOOK_LIST_JUSTIFY'
export const NOTEBOOK_LIST_SORTBY      = 'NOTEBOOK_LIST_SORTBY'
export const NOTEBOOK_LIST_FILTER      = 'NOTEBOOK_LIST_FILTER'

export const NOTEBOOK_REMOVE_BEGIN     = 'NOTEBOOK_REMOVE_BEGIN'
export const NOTEBOOK_REMOVE_FAILURE   = 'NOTEBOOK_REMOVE_FAILURE'
export const NOTEBOOK_REMOVE_SUCCESS   = 'NOTEBOOK_REMOVE_SUCCESS'